apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-git
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: petclinic-git
  template:
    metadata:
      labels:
        app: petclinic-git
    spec:
      containers:
      - name: petclinic-git
        image: docker.pkg.github.com/canarysplayground/spring-petclinic/petclinic:${{ github.run_number }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-git
  labels:
    app: petclinic-git
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-git
