name: Spring-Petclinic

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
    - uses: actions/checkout@v2
   
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: petclinic
        path: target
    
    #- name: Azure WebApp Deploy
    #  uses: Azure/webapps-deploy@v2
    #  with:
    #      app-name: petcliinic
    #      publish-profile: ${{secrets.WEB_APP_PUBLISH_PROFILE}}
    #      package: target/*.jar
